// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_App1_2_H
#define WINRT_App1_2_H
#include "winrt/impl/Microsoft.UI.Xaml.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.1.h"
#include "winrt/impl/App1.1.h"
WINRT_EXPORT namespace winrt::App1
{
    struct WINRT_IMPL_EMPTY_BASES MainWindow : winrt::App1::IMainWindow,
        impl::base<MainWindow, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<MainWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        MainWindow(std::nullptr_t) noexcept {}
        MainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::App1::IMainWindow(ptr, take_ownership_from_abi) {}
        MainWindow();
    };
    struct WINRT_IMPL_EMPTY_BASES XamlMetaDataProvider : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider
    {
        XamlMetaDataProvider(std::nullptr_t) noexcept {}
        XamlMetaDataProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider(ptr, take_ownership_from_abi) {}
        XamlMetaDataProvider();
    };
}
#endif
